version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/installapache
      timeout: 300
      runas: root
    - location: scripts/restartapache
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/startapache
      timeout: 300
      runas: root
